
const sidebars = {
  tutorialSidebar: [
    { type: 'doc', id: 'intro/intro', label: 'Introduction' },
    {
      type: 'category',
      label: 'Documentation',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'topics' }],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsible: true,
      collapsed: false,
      items: [
  {
    "type": "category",
    "label": "deep-learning-for-coders-with-fastai-and-pytorch--ai-applications-without-a-phd",
    "collapsible": true,
    "collapsed": false,
    "items": [
      {
        "type": "category",
        "label": "intro",
        "items": [
          {
            "type": "doc",
            "id": "resources/deep-learning-for-coders-with-fastai-and-pytorch--ai-applications-without-a-phd/intro/rosenblatt-s",
            "label": "rosenblatt-s"
          }
        ]
      },
      {
        "type": "category",
        "label": "production",
        "items": [
          {
            "type": "doc",
            "id": "resources/deep-learning-for-coders-with-fastai-and-pytorch--ai-applications-without-a-phd/production/parallel-distributed-processing--pdp-",
            "label": "parallel-distributed-processing--pdp-"
          }
        ]
      }
    ]
  }
]
    },
  ],
};

export default sidebars;
