const sidebars = {
  tutorialSidebar: [
    { type: 'doc', id: 'intro/intro', label: 'Introduction' }, // Correct intro path
    {
      type: 'category',
      label: 'Documentation',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'topics' }], // Use "topics"
    },
  ],
};

export default sidebars;